version: '3'
services:
  iga:
    build: .
    volumes:
      - ./:/workspace/
      #- /tmp/.X11-unix:/tmp/.X11-unix # comment out if on linux.
    #command: "bash -c 'jupyter notebook  --no-browser --ip=0.0.0.0 --port=8000 --allow-root --notebook-dir=/workspace/notes --NotebookApp.token=\"\"'"
    #command: "bash -c 'jupyter lab --no-browser --ip=0.0.0.0 --port=8000 --allow-root --notebook-dir=/workspace/notes --NotebookApp.token=\"\"'"
    stdin_open: true
    tty: true
    ports:
      - 8001:8001
    environment:
      - DISPLAY=$DISPLAY